# NUMPY ARRAYS 

In [4]:
lis = [1,2,3]
lis

[1, 2, 3]

In [7]:
import numpy as np
arr = np.array(lis)
arr

array([1, 2, 3])

In [10]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]
mymat
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,11,2) # the last argument is steps 

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.linspace(0,5,10)  
# the last argument in number we want between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.random.rand(5)

array([0.51221622, 0.47473586, 0.81891482, 0.63453502, 0.48117606])

In [34]:
np.random.rand(2,2) # only postive

array([[0.13837261, 0.02834521],
       [0.63812767, 0.87137225]])

In [37]:
np.random.randn(2,2) # positive with negative

array([[-0.73896282,  0.08316861],
       [ 0.2240865 , -0.07443538]])

In [42]:
np.random.randint(1,10) #one is include 10 no 

7

In [43]:
np.random.randint(1,10,10) #one is include 10 no 

array([6, 3, 4, 4, 8, 2, 9, 1, 1, 1])

In [45]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr = np.random.randint(0,50,10)
ranarr

array([31, 42, 40, 47, 48, 19,  2, 30, 11, 41])

In [63]:
arr = arr.reshape(5,5) #changer la forme 

In [54]:
ranarr.max()

48

In [55]:
ranarr.min()

2

In [56]:
ranarr.argmax()

4

In [58]:
ranarr.argmin()

6

In [65]:
arr.shape

(5, 5)

In [66]:
arr.dtype

dtype('int64')

In [67]:
from numpy.random import randint
randint(2,10)

3