In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[5:6]

array([5])

In [13]:
arr[0:5]=100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr =np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
sliceofarr= arr[0:6]  # don't copie reference 
sliceofarr 

array([0, 1, 2, 3, 4, 5])

In [20]:
sliceofarr[:]

array([0, 1, 2, 3, 4, 5])

In [22]:
sliceofarr[:] = 99
sliceofarr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copie  = arr.copy()
arr
arr_copie

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copie[:]=200
arr_copie
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

 # MATRIX 

In [32]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
array2[0]

array([1, 2, 3])

In [36]:
array2[2,1] # better than using between brackets 

8

In [44]:
array2[0:,:1]

array([[1],
       [4],
       [7]])

# CONDITIONAL SELECTION 

In [58]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bol = ar > 5 
bol

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
 ar[bol]


array([ 6,  7,  8,  9, 10])

In [63]:
ar[ar>5]

array([ 6,  7,  8,  9, 10])

In [64]:
ar[ar<3]

array([1, 2])

In [67]:
ar1 = np.arange(50).reshape(5,10)
ar1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
ar1[1:5,3:7]

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46]])