# NUMPY OPERATION 
 * ARRAY WITH ARRAY 
 * ARRAY WITH SCALARS
 * UNIVERSAL ARRAY FUNCTION 

In [1]:
import numpy as np 

In [16]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr *arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [17]:
 arr / arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr + 10 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# UNIVERSAL FUNCTION 

In [22]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [23]:
np.max(arr)

10

In [24]:
np.min(arr)

1

In [26]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])